sudo: false
dist: trusty
env:
  global:
    TERRAFORM_VERSION: "0.9.11"

install:
- mkdir bin
- curl -o ./bin/terraform.zip "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
- unzip -d ./bin ./bin/terraform.zip
- chmod +x ./bin/terraform

script:
- ./bin/terraform validate
